apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: test-argo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: test-rai
  source:
    repoURL: https://apache.github.io/superset
    targetRevision: 2.1.0
    chart: superset
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: superset-rai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      # - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
