apiVersion: "argoproj.io/v1alpha1"
kind: AppProject
metadata:
  name: test-argo-rai-superset
  namespace: argocd
spec:
  description: "Test Superset project"
  sourceRepos:
    - https://github.com/raisantos/argocd.git
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
